spring:
  application:
    name:
      WeatherApi
  datasource:
    url: jdbc:h2:mem:mydb;mode=oracle
    username: tiila
    password: root
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true